export const CREATE_REGISTER_REQUEST = "CREATE_REGISTER_REQUEST";
export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const VERIFY_OTP = "VERIFY_OTP";
export const RESET_PASSWORD = "RESET_PASSWORD";
